# Generated by Django 4.0.6 on 2022-07-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robota_app', '0002_jobskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(blank=True, null=True)),
                ('lname', models.TextField(blank=True, null=True)),
                ('cv', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.PositiveIntegerField()),
                ('password', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField()),
                ('companyJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robota_app.companyjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robota_app.user')),
            ],
        ),
    ]
