# Generated by Django 4.0.6 on 2022-07-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robota_app', '0006_companyjob_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
